export const fallbackSppgData = [
  {
    id: "sppg-kebayoran",
    name: "SPPG Kebayoran Baru",
    location: "Jakarta Selatan, DKJ Jakarta",
    info: "Melayani 2 SD, 2 SMP, dan 1 SMA",
    capacity: "Kapasitas: 3,000 MBG/hari",
    lat: -6.2447,
    lng: 106.7997,
    schools: ["school-01", "school-02", "school-03"],
  },
  {
    id: "sppg-srengseng",
    name: "SPPG Srengseng",
    location: "Jakarta Barat, DKJ Jakarta",
    info: "Melayani 2 SD dan 1 SMP",
    capacity: "Kapasitas: 3,000 MBG/hari",
    lat: -6.2105,
    lng: 106.7599,
    schools: ["school-04", "school-05"],
  },
];

export const fallbackSchoolData = [
  {
    id: "school-01",
    name: "SDN Kebayoran 01",
    location: "Jakarta Selatan, DKJ Jakarta",
    info: "Mitra distribusi SPPG Kebayoran Baru",
    capacity: "Jumlah siswa: 420 siswa",
    lat: -6.2365,
    lng: 106.7893,
    sppgId: "sppg-kebayoran",
  },
  {
    id: "school-02",
    name: "SMPN Kebayoran 03",
    location: "Jakarta Selatan, DKJ Jakarta",
    info: "Mitra distribusi SPPG Kebayoran Baru",
    capacity: "Jumlah siswa: 510 siswa",
    lat: -6.2552,
    lng: 106.8126,
    sppgId: "sppg-kebayoran",
  },
  {
    id: "school-03",
    name: "SMAN Tebet 05",
    location: "Jakarta Selatan, DKJ Jakarta",
    info: "Mitra distribusi SPPG Kebayoran Baru",
    capacity: "Jumlah siswa: 610 siswa",
    lat: -6.2292,
    lng: 106.8324,
    sppgId: "sppg-kebayoran",
  },
  {
    id: "school-04",
    name: "SDN Srengseng 11",
    location: "Jakarta Barat, DKJ Jakarta",
    info: "Mitra distribusi SPPG Srengseng",
    capacity: "Jumlah siswa: 398 siswa",
    lat: -6.1988,
    lng: 106.7515,
    sppgId: "sppg-srengseng",
  },
  {
    id: "school-05",
    name: "SMPN Srengseng 02",
    location: "Jakarta Barat, DKJ Jakarta",
    info: "Mitra distribusi SPPG Srengseng",
    capacity: "Jumlah siswa: 452 siswa",
    lat: -6.2217,
    lng: 106.7734,
    sppgId: "sppg-srengseng",
  },
];
