export const fallbackSppgUnits = [
  {
    id: 1,
    title: "Dapur Umum Sehat Jakarta",
    location: "Jakarta Pusat",
    image:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=420&q=80",
    status: "ACTIVE",
    capacity: "CAPACITY: 5000",
    schoolsServed: 2,
    distributedPortions: "-",
    rating: "-",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Ayam Teriyaki",
    menuDetail: "Telur Dadar, Pisang",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 2,
    title: "Dapur Gizi Nusantara Bekasi",
    location: "Bekasi Selatan",
    image:
      "https://images.unsplash.com/photo-1556911220-bda9f7f7597e?auto=format&fit=crop&w=420&q=80",
    status: "ACTIVE",
    capacity: "CAPACITY: 3000",
    schoolsServed: 2,
    distributedPortions: "-",
    rating: "-",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Semur Daging",
    menuDetail: "Tahu, Semangka",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 3,
    title: "Dapur Sehat Depok Mandiri",
    location: "Depok",
    image:
      "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=420&q=80",
    status: "ACTIVE",
    capacity: "CAPACITY: 2500",
    schoolsServed: 2,
    distributedPortions: "-",
    rating: "-",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Ayam Kecap",
    menuDetail: "Tempe Goreng, Apel",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
];

export const fallbackSchoolUnits = [
  {
    id: 1,
    title: "SDN Sukamaju 01",
    location: "Jakarta Pusat",
    image:
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR UMUM SEHAT JAKARTA",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Ayam Teriyaki",
    menuDetail: "Telur Dadar, Pisang",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 2,
    title: "SMPN 2 Nusantara",
    location: "Jakarta Pusat",
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR UMUM SEHAT JAKARTA",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Merah + Ikan Tongkol Balado",
    menuDetail: "Tempe Orek, Jeruk",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 3,
    title: "SDN Mekarsari 03",
    location: "Bekasi",
    image:
      "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR GIZI NUSANTARA BEKASI",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Semur Daging",
    menuDetail: "Tahu, Semangka",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 4,
    title: "SDN Harapan Bangsa",
    location: "Bekasi Utara",
    image:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR GIZI NUSANTARA BEKASI",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Ayam Bakar",
    menuDetail: "Capcay, Pisang",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 5,
    title: "SMKN 1 Teknologi Depok",
    location: "Depok",
    image:
      "https://images.unsplash.com/photo-1502791451866-7bd8c1df43a7?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR SEHAT DEPOK MANDIRI",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Putih + Ayam Kecap",
    menuDetail: "Tempe Goreng, Apel",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 6,
    title: "SDN Cempaka Putih",
    location: "Depok",
    image:
      "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: DAPUR SEHAT DEPOK MANDIRI",
    students: "Data siswa belum tersedia",
    menuLabel: "Menu Mingguan (28 Apr - 2 Mei)",
    menuTitle: "Nasi Merah + Pepes Ikan",
    menuDetail: "Sayur Lodeh, Pisang",
    calories: "650 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
];
