export const fallbackMapData = {
  kitchens: [
    {
      id: "sppg-jkt-001",
      name: "Dapur Umum Sehat Jakarta",
      city: "Jakarta Pusat, DKI Jakarta",
      coverage: "Melayani 2 sekolah",
      capacity: "5,000 MBG/hari",
      lat: -6.2088,
      lng: 106.8456,
      left: "42%",
      top: "30%",
    },
    {
      id: "sppg-bks-001",
      name: "Dapur Gizi Nusantara Bekasi",
      city: "Bekasi Selatan, Jawa Barat",
      coverage: "Melayani 2 sekolah",
      capacity: "3,000 MBG/hari",
      lat: -6.2415,
      lng: 106.9924,
      left: "64%",
      top: "40%",
    },
    {
      id: "sppg-dpk-001",
      name: "Dapur Sehat Depok Mandiri",
      city: "Depok, Jawa Barat",
      coverage: "Melayani 2 sekolah",
      capacity: "2,500 MBG/hari",
      lat: -6.3728,
      lng: 106.8317,
      left: "52%",
      top: "62%",
    },
  ],
  schools: [
    {
      id: "sdn-sukamaju-01",
      name: "SDN Sukamaju 01",
      city: "Jakarta Pusat, DKI Jakarta",
      level: "SD",
      students: "Data siswa belum tersedia",
      lat: -6.21,
      lng: 106.85,
      left: "36%",
      top: "22%",
    },
    {
      id: "smpn-nusantara-02",
      name: "SMPN 2 Nusantara",
      city: "Jakarta Pusat, DKI Jakarta",
      level: "SMP",
      students: "Data siswa belum tersedia",
      lat: -6.22,
      lng: 106.84,
      left: "48%",
      top: "26%",
    },
    {
      id: "sdn-mekarsari-03",
      name: "SDN Mekarsari 03",
      city: "Bekasi, Jawa Barat",
      level: "SD",
      students: "Data siswa belum tersedia",
      lat: -6.25,
      lng: 106.99,
      left: "70%",
      top: "36%",
    },
    {
      id: "sdn-harapan-bangsa",
      name: "SDN Harapan Bangsa",
      city: "Bekasi Utara, Jawa Barat",
      level: "SD",
      students: "Data siswa belum tersedia",
      lat: -6.235,
      lng: 107.0,
      left: "74%",
      top: "52%",
    },
    {
      id: "smkn-teknologi-depok",
      name: "SMKN 1 Teknologi Depok",
      city: "Depok, Jawa Barat",
      level: "SMK",
      students: "Data siswa belum tersedia",
      lat: -6.39,
      lng: 106.82,
      left: "48%",
      top: "72%",
    },
    {
      id: "sdn-cempaka-putih",
      name: "SDN Cempaka Putih",
      city: "Depok, Jawa Barat",
      level: "SD",
      students: "Data siswa belum tersedia",
      lat: -6.36,
      lng: 106.84,
      left: "60%",
      top: "70%",
    },
  ],
  selectedKitchenId: "sppg-jkt-001",
};
