export const fallbackMapData = {
  kitchens: [
    {
      id: "kebayoran",
      name: "SPPG Kebayoran Baru",
      city: "Jakarta Selatan, DKJ Jakarta",
      coverage: "Melayani 2 SD, 2 SMP, dan 1 SMA",
      capacity: "3,000 MBG/hari",
      left: "58%",
      top: "36%",
    },
    {
      id: "srengseng",
      name: "SPPG Srengseng",
      city: "Jakarta Barat, DKJ Jakarta",
      coverage: "Melayani 2 SD dan 1 SMP",
      capacity: "3,000 MBG/hari",
      left: "34%",
      top: "52%",
    },
    {
      id: "tebet",
      name: "SPPG Tebet Kebon Baru",
      city: "Jakarta Selatan, DKJ Jakarta",
      coverage: "Melayani 2 SD, 1 SMP, dan 1 SMA",
      capacity: "3,000 MBG/hari",
      left: "67%",
      top: "48%",
    },
  ],
  schools: [
    {
      id: "sd-01",
      name: "SDN Kebayoran 01",
      city: "Jakarta Selatan, DKJ Jakarta",
      level: "SD",
      students: "420 siswa",
      left: "22%",
      top: "30%",
    },
    {
      id: "sd-02",
      name: "SMPN Kebayoran 03",
      city: "Jakarta Selatan, DKJ Jakarta",
      level: "SMP",
      students: "510 siswa",
      left: "40%",
      top: "26%",
    },
    {
      id: "sd-03",
      name: "SMAN Tebet 05",
      city: "Jakarta Selatan, DKJ Jakarta",
      level: "SMA",
      students: "610 siswa",
      left: "48%",
      top: "64%",
    },
    {
      id: "sd-04",
      name: "SDN Srengseng 11",
      city: "Jakarta Barat, DKJ Jakarta",
      level: "SD",
      students: "398 siswa",
      left: "72%",
      top: "24%",
    },
    {
      id: "sd-05",
      name: "SMPN Srengseng 02",
      city: "Jakarta Barat, DKJ Jakarta",
      level: "SMP",
      students: "452 siswa",
      left: "77%",
      top: "68%",
    },
  ],
  selectedKitchenId: "kebayoran",
};
