export const fallbackSppgUnits = [
  {
    id: 1,
    title: "SPPG Kemang",
    location: "Jakarta Selatan",
    image:
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=420&q=80",
    status: "HYGIENE CERTIFIED",
    capacity: "CAPACITY: 4K",
    schoolsServed: 12,
    distributedPortions: "3.094",
    rating: "4.5/5",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Kuning + Ayam Goreng",
    menuDetail: "Sayur Bayam, Tempe Bacem, Buah Pisang",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 2,
    title: "SPPG Sawah Besar",
    location: "Jakarta Pusat",
    image:
      "https://images.unsplash.com/photo-1556911220-bda9f7f7597e?auto=format&fit=crop&w=420&q=80",
    status: "HYGIENE CERTIFIED",
    capacity: "CAPACITY: 5K",
    schoolsServed: 9,
    distributedPortions: "4.250",
    rating: "5/5",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Daging Semur",
    menuDetail: "Sayur Buncis, Tahu, Buah Jeruk",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 3,
    title: "SPPG Tanjung Duren Utara",
    location: "Jakarta Barat",
    image:
      "https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=420&q=80",
    status: "HYGIENE CERTIFIED",
    capacity: "CAPACITY: 5K",
    schoolsServed: 11,
    distributedPortions: "3.500",
    rating: "5/5",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Ikan Dori",
    menuDetail: "Sayur Capcay, Tahu Crispy, Buah Melon",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 4,
    title: "SPPG Tebet",
    location: "Jakarta Selatan",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=420&q=80",
    status: "HYGIENE CERTIFIED",
    capacity: "CAPACITY: 4K",
    schoolsServed: 10,
    distributedPortions: "3.860",
    rating: "4.7/5",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Uduk + Telur Balado",
    menuDetail: "Lalapan, Tempe Orek, Buah Pepaya",
    calories: "550 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 5,
    title: "SPPG Palmerah",
    location: "Jakarta Barat",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=420&q=80",
    status: "HYGIENE CERTIFIED",
    capacity: "CAPACITY: 5.5K",
    schoolsServed: 13,
    distributedPortions: "4.980",
    rating: "4.9/5",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Ayam Panggang",
    menuDetail: "Sayur Asem, Tahu, Buah Semangka",
    calories: "560 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
];

export const fallbackSchoolUnits = [
  {
    id: 1,
    title: "SMKN 1 Jakarta Pusat",
    location: "Jakarta Pusat",
    image:
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: SPPG SAWAH BESAR",
    students: "1.639 SISWA",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Kuning + Ayam Goreng",
    menuDetail: "Sayur Bayam, Tempe Bacem, Buah Pisang",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 2,
    title: "SMKN 48 Jakarta",
    location: "Jakarta Timur",
    image:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: SPPG DUREN SAWIT",
    students: "735 SISWA",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Daging Semur",
    menuDetail: "Sayur Buncis, Tahu, Buah Jeruk",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 3,
    title: "SDN 03 Pengadegan",
    location: "Jakarta Selatan",
    image:
      "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: SPPG KALIBATA",
    students: "889 SISWA",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Ikan Dori",
    menuDetail: "Sayur Capcay, Tahu Crispy, Buah Melon",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 4,
    title: "SMPN 115 Jakarta",
    location: "Jakarta Selatan",
    image:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: SPPG TEBET",
    students: "1.038 SISWA",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Daun Jeruk + Rendang Ayam",
    menuDetail: "Tumis Wortel, Tahu Tempe, Buah Apel",
    calories: "540 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
  {
    id: 5,
    title: "SMPN 9 Jakarta",
    location: "Jakarta Barat",
    image:
      "https://images.unsplash.com/photo-1502791451866-7bd8c1df43a7?auto=format&fit=crop&w=420&q=80",
    kitchen: "KITCHEN: SPPG PALMERAH",
    students: "1.102 SISWA",
    menuLabel: "Menu Hari Ini: Senin, 25 Mei",
    menuTitle: "Nasi Putih + Ayam Teriyaki",
    menuDetail: "Sayur Asem, Tahu, Buah Semangka",
    calories: "550 kkal",
    nutrition: "Target Nutrisi: 100%",
  },
];
